import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "AION-File: AI ilə file Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}